name: Docker Build and Push to ACR

on:
  push:
    branches:
      - main  # Set to your default branch

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Log in to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: citrusi.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t citrusi.azurecr.io/citrusi_web:${{ github.sha }} .
        docker push citrusi.azurecr.io/citrusi_web:${{ github.sha }}

    - name: Deploy to Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SERVER_PASSWORD }}
        script: |
          docker pull citrusi.azurecr.io/citrusi_web:${{ github.sha }}
          docker stop citrusi_web || true
          docker rm citrusi_web || true
          docker run --name citrusi_web -d -p 80:80 citrusi.azurecr.io/citrusi_web:${{ github.sha }}
